[package]
name = "py-emu-lib"
version = "0.1.0"
edition = "2021"

[lib]
name = "py_emu_lib"
crate-type = ["cdylib"]

[dependencies]
emu_lib = { path = "../" }
pyo3 = { version = "0.20.3", features = ["extension-module"] }
